spring.application.name=backendcomedor
server.servlet.context-path=/api/v1
# NEONTECH DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:datos.sql
spring.jpa.defer-datasource-initialization=true

RENIEC_TOKEN=${RENIEC_TOKEN}